name: Deployment Workflow
on:
    push:
        branches: [master]

jobs:
    deply_job:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Establish a Connection to Server and Update Website
              uses: appleboy/ssh-action@master
              with:
                  host: 130.185.76.173
                  username: root
                  key: ${{secrets.SSH_KEY}}
                  port: 22
                  script: |
                      cd /repos/code-star-summer-1400
                      git fetch
                      git checkout master
                      git pull origin master
                      cp -a . /var/fun/bijanprogrammer.com/html/code-star-summer-1400/
